Input added
sol-wizard/Blotz-Task-App pull request #132
Opened 2024-11-20 09:35 UTC by survivzhang

Finish the input components

2024-11-21 22:59 UTC, Ben0189 requested changes

2024-11-21 22:59 UTC, Ben0189 commented on blotztask-ui/src/app/add-task/addTask.tsx
> +import { Input } from '@/components/ui/input';
not recommend to put this in separate component. Later on we gonna build a form to wrap those input

2024-11-22 05:46 UTC, survivzhang commented
update finish

2024-11-22 10:37 UTC, sol-wizard requested changes

2024-11-22 10:37 UTC, sol-wizard commented on .DS_Store
we dont need this D store in our repo. please remove

2024-11-22 22:54 UTC, survivzhang commented
<img width="1440" alt="Screenshot 2024-11-23 at 6 53 13 AM" src="https://github.com/user-attachments/assets/d10a4889-5b2c-4f75-9294-9b9109a49955">

2024-11-22 23:02 UTC, survivzhang commented on .DS_Store
I didn't find it in my local document

2024-11-22 23:21 UTC, survivzhang commented on blotztask-ui/src/app/add-task/addTask.tsx
> +import { Input } from '@/components/ui/input';
Already  combine two documents

2025-01-22 10:15 UTC, PeterOu8 commented
The PR has now been closed due to design update.

2025-01-22 10:15 UTC, closed without merging