#230 refactor register form to use react hook form
sol-wizard/Blotz-Task-App pull request #140
Opened 2024-11-29 15:58 UTC by Xiaoxiao-Lin-Jessica

A local test was done, but the UI still needs fixing and adjusting.

Email validation:
![image](https://github.com/user-attachments/assets/87846b46-600b-471f-87eb-1b65d88ca381)
![image](https://github.com/user-attachments/assets/c2f0d204-5486-4377-bc2e-5572e474e6ff)
![image](https://github.com/user-attachments/assets/ad7daf25-07c3-4954-bdea-9993e8d73de2)

Password validation:
![image](https://github.com/user-attachments/assets/b387b0bb-9f7e-45c0-a7f7-1ef72bfce4f5)
![image](https://github.com/user-attachments/assets/65fc667d-e4e0-4024-b657-19f312dd53de)
![image](https://github.com/user-attachments/assets/81e2c61f-5118-4640-854d-56bd47501a4f)
![image](https://github.com/user-attachments/assets/78fb0610-2a8e-4205-8796-7d517b40cd5e)

If all validation passes, it shows register successfully.
![image](https://github.com/user-attachments/assets/5e0d9038-aee9-407d-acee-7484461485a3)

Testing email and password are:
123@gmail.com
1q2w3e4rQ*

2024-12-05 12:33 UTC, Ben0189 submitted a review, later dismissed

2024-12-13 11:18 UTC, Xiaoxiao-Lin-Jessica commented on blotztask-ui/src/app/signup/page.tsx
> +    .regex(
use zod custom validation to replacing regex method

2024-12-13 11:20 UTC, Xiaoxiao-Lin-Jessica commented
Update:
1. Fixed email and password prompt UI with better and similar design.
2. Zod custom validation method replaced regex method.
3. Fixed catch error prompt UI with similar design.

2024-12-14 00:12 UTC, sol-wizard requested changes

2024-12-20 11:25 UTC, Xiaoxiao-Lin-Jessica commented
Update:

Change the global error prompt to the same UI design as sign-in page.
change custom validation to Zod.

2025-04-02 06:37 UTC, closed without merging