feat: monthly stats page fetch data
sol-wizard/Blotz-Task-App pull request #154
Opened 2024-12-13 23:47 UTC by HoshinoIzumi

<img width="1358" alt="Screenshot 2024-12-14 at 10 33 18" src="https://github.com/user-attachments/assets/4d22c30f-5c0b-454c-aa85-10920455ac58" />

Fetch data from backend:
- TaskService
- created monthly stats DTO
- monthly stats Page

2024-12-21 09:15 UTC, PeterOu8 requested changes

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/services/taskService.ts
> +    //console.log('Raw response:', response);
Please remove unused consoles and comments.

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/services/taskService.ts
> +    //console.log(`Fetching monthly stats from: ${url}`);
Please remove unused consoles and comments.

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/services/taskService.ts
> +    const response = await fetch(url, {
Call fetchWIthAuth function to include error handling in your method

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/services/taskService.ts
> +      const getCookie = (name: string): string | null => {
What are the cookies for? Could you please briefly explain the intended functionalities of these?

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/app/monthly-stats/page.tsx
> +    const fetchStats = async () => {
Move this function out of the useEffect layer to improve readability.

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/app/monthly-stats/page.tsx
> +    const fetchStats = async () => {
I have filtered the data in the format. So, just call the endpoint and store it in a DTO state should be sufficient.
![image](https://github.com/user-attachments/assets/d354407e-bf7d-4d3c-9420-f80f09b2b5a8)

2024-12-21 09:15 UTC, PeterOu8 commented on blotztask-ui/src/app/monthly-stats/page.tsx
> +  const [totalUncompleted, setTotalUncompleted] = useState(0);
You can remove all three states and just keep one state for your fetched result and store it in DTO type.

2025-04-02 06:37 UTC, Ben0189 commented
page has been removed

2025-04-02 06:37 UTC, closed without merging