refactor the task card component
sol-wizard/Blotz-Task-App pull request #164
Opened 2024-12-29 00:37 UTC by nxn-nicole

2025-01-03 08:16 UTC, sol-wizard requested changes

2025-01-03 08:16 UTC, sol-wizard commented on blotztask-ui/src/app/today/page.tsx
> +  const [tasks] = useState<TaskDTO[]>([]); // Store all tasks here
Why do you remove the set task code ? looks like you accidentally remove it when solving merge conflict 

Tips: After solve conflict always test locally to see if things changes , in this case you need to test the progress bar

2025-01-03 11:01 UTC, nxn-nicole commented on blotztask-ui/src/app/today/page.tsx
> +  const [tasks] = useState<TaskDTO[]>([]); // Store all tasks here
It seems we don't need the tasks and setTasks. I have deleted this. But it seems it can't fetch data to the page. I don't know why there are no tasks shown in the page even after I changed the database.

2025-01-07 10:12 UTC, sol-wizard approved these changes

2025-01-07 10:13 UTC, merged